### ISSUE TITLE
requirements.txt is missing the onnx module

### ISSUE THREAD

**Issue by aychun** [sony/model_optimization#1058]
### Issue Type

Others

### Source

source

### MCT Version

2.0.0

### OS Platform and Distribution

macOS 14.3.1

### Python version

3.10.11

### Describe the issue

```shell
requirement.txt is missing the onnx library and will raise a ModuleNotFoundError in the example_keras_yolov8n tutorial
```

### Expected behaviour

```shell
Following the notebook will run without manually having to install the onnx module
```

### Code to reproduce the issue

```shell
import model_compression_toolkit as mct
```

or follow the [example_keras_yolov8n.ipynb tutorial ](https://colab.research.google.com/github/sony/model_optimization/blob/main/tutorials/notebooks/keras/ptq/example_keras_yolov8n.ipynb) and the _Post training quantization using Model Compression Toolkit_ section will raise a ModuleNotFoundError

### Log output

```shell
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-d0b3af1c43fe> in <cell line: 1>()
----> 1 import model_compression_toolkit as mct
      2 from typing import Iterator, Tuple, List
      3 
      4 REPRESENTATIVE_DATASET_FOLDER = './coco/val2017/'
      5 REPRESENTATIVE_DATASET_ANNOTATION_FILE = './coco/annotations/instances_val2017.json'

10 frames
/content/./local_mct/model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py in <module>
     17 
     18 import torch.nn
---> 19 import onnx
     20 
     21 from mct_quantizers import PytorchActivationQuantizationHolder, PytorchQuantizationWrapper

ModuleNotFoundError: No module named 'onnx'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.
```

**Comment by reuvenperetz** [comment]
Will be fixed by #1060

**Comment by aychun** [comment]
@reuvenperetz 
Thank you for checking out and fixing the issue. 
If you don't mind, I have a quick question. What would be the proper way / channel to ask questions regarding the MCT? Could I open an "issue" in this repository to ask for some help? Or is there any forum / discussion board where I could ask some general questions?

I appreciate your work and hope to make a contribution in the future. I will closed the PR I submitted but leave this issue open for now :)

**Comment by reuvenperetz** [comment]
Currently, the best way to ask questions is using an issue.
Your contributions are greatly appreciated! Please don't hesitate to ask any questions :)
