### ISSUE TITLE
How to use MCT to train a custom yolov8n model?

### ISSUE THREAD

**Issue by t56gary** [sony/model_optimization#1139]
### Issue Type

Feature Request

### Source

pip (model-compression-toolkit)

### MCT Version

2.1.0

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.10

### Describe the issue

Hi,
I am trying to deploy a trained custom YOLOv8n model on the IMX500 platform and have encountered some issues during the process.
I have trained a custom YOLOv8n model using Ultralytics, and I tried using all the methods in the MCT tutorials to train and compress our model but haven't been successful. 
The error returned is: "NotImplementedError: Module [YOLO] is missing the required 'forward' function."
Could you please provide more details on how to use MCT to train a custom YOLO model? 
Specifically, I need help with correctly loading the model and properly setting the configuration for quantization.

### Code to reproduce the issue

```python
import torch
from ultralytics import YOLO
import model_compression_toolkit as mct
from typing import Iterator, Tuple, List
import os
import yaml
import cv2
import numpy as np

# Modify to your custom dataset path
DATASET_CONFIG_FILE = os.path.abspath("dataset_yolov8/data.yaml")  # Change path to your dataset config file
BATCH_SIZE = 4
n_iters = 20

# Load custom model
model_path = os.path.abspath("runs/detect/train/weights/best.pt")  # Replace with your model path
model = YOLO(model_path)

# # Switch model to evaluation mode
# model.eval()

# Read dataset config file
with open(DATASET_CONFIG_FILE, 'r') as f:
    dataset_config = yaml.safe_load(f)
train_images_path = os.path.abspath("dataset_yolov8/train/images")
val_images_path = os.path.abspath("dataset_yolov8/valid/images")
class_names = dataset_config['names']

# Custom dataset generator
def custom_dataset_generator(images_path: str, batch_size: int):
    image_files = [os.path.join(images_path, img) for img in os.listdir(images_path) if img.endswith('.jpg') or img.endswith('.png')]
    np.random.shuffle(image_files)
    
    def preprocess(image_path):
        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (640, 640))
        image = image.astype(np.float32) / 255.0
        image = np.transpose(image, (2, 0, 1))  # HWC to CHW
        return image
    
    for i in range(0, len(image_files), batch_size):
        batch_images = [preprocess(img_path) for img_path in image_files[i:i+batch_size]]
        yield np.stack(batch_images, axis=0)

# Define representative dataset generator
def get_representative_dataset(n_iter: int, dataset_loader: Iterator[Tuple]):
    def representative_dataset() -> Iterator[List]:
        ds_iter = iter(dataset_loader)
        for _ in range(n_iter):
            yield [next(ds_iter)]
    return representative_dataset

# Load custom dataset
representative_dataset = custom_dataset_generator(val_images_path, BATCH_SIZE)

# Get representative dataset generator
representative_dataset_gen = get_representative_dataset(n_iter=n_iters, dataset_loader=representative_dataset)

# Set IMX500-v1 TPC
tpc = mct.get_target_platform_capabilities(fw_name="pytorch", target_platform_name='imx500', target_platform_version='v1')

# # Mixed precision quantization configuration
# mp_config = mct.core.MixedPrecisionQuantizationConfig(num_of_images=5, use_hessian_based_scores=False)
# config = mct.core.CoreConfig(mixed_precision_config=mp_config, quantization_config=mct.core.QuantizationConfig(shift_negative_activation_correction=True))

# # Resource utilization setting
# resource_utilization_data = mct.core.pytorch_resource_utilization_data(in_model=model, representative_data_gen=representative_dataset_gen, core_config=config, target_platform_capabilities=tpc)
# resource_utilization = mct.core.ResourceUtilization(weights_memory=resource_utilization_data.weights_memory * 0.75)

# Perform post-training quantization
quant_model, quantization_info_ = mct.ptq.pytorch_post_training_quantization(in_module=model_path, representative_data_gen=representative_dataset_gen, target_platform_capabilities=tpc)
print('Quantized model is ready')

# Wrap the quantized model and perform post-processing
from model_optimization.tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import PostProcessWrapper

score_threshold = 0.001
iou_threshold = 0.7
max_detections = 300

# Get device
from model_compression_toolkit.core.pytorch.pytorch_device_config import get_working_device
device = get_working_device()

quant_model_pp = PostProcessWrapper(model=quant_model, score_threshold=score_threshold, iou_threshold=iou_threshold, max_detections=max_detections).to(device=device)

mct.exporter.pytorch_export_model(model=quant_model_pp,
                                  save_model_path=os.path.abspath("runs/detect/train/weights/qmodel_pp.onnx"),
                                  repr_dataset=representative_dataset_gen)
```

### Log output

100 epochs completed in 3.564 hours.
Optimizer stripped from runs/detect/train32/weights/last.pt, 6.3MB
Optimizer stripped from runs/detect/train32/weights/best.pt, 6.2MB

Validating runs/detect/train32/weights/best.pt...
Ultralytics YOLOv8.2.54 🚀 Python-3.10.12 torch-2.3.1+cu118 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 64/64 [00:07<
                   all       2046       2132      0.972      0.966      0.983      0.709
Speed: 0.2ms preprocess, 0.8ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to runs/detect/train32
Traceback (most recent call last):
  File "/home/gary/tensorflow_test/yolov8n_quantized.py", line 72, in <module>
    quant_model, quantization_info_ = mct.ptq.pytorch_post_training_quantization(in_module=model, representative_data_gen=representative_dataset_gen,target_platform_capabilities=tpc)
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/ptq/pytorch/quantization_facade.py", line 112, in pytorch_post_training_quantization
    tg, bit_widths_config, _ = core_runner(in_model=in_module,
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/core/runner.py", line 105, in core_runner
    graph = graph_preparation_runner(in_model,
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/core/graph_prep_runner.py", line 69, in graph_preparation_runner
    graph = read_model_to_graph(in_model,
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/core/graph_prep_runner.py", line 200, in read_model_to_graph
    graph = fw_impl.model_reader(in_model,
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/core/pytorch/pytorch_implementation.py", line 148, in model_reader
    return model_reader(_module, representative_data_gen, self.to_numpy, self.to_tensor)
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/core/pytorch/reader/reader.py", line 153, in model_reader
    fx_model = fx_graph_module_generation(model, representative_data_gen, to_tensor)
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/model_compression_toolkit/core/pytorch/reader/reader.py", line 90, in fx_graph_module_generation
    symbolic_traced = symbolic_trace(pytorch_model)
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 1193, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 793, in trace
    (self.create_arg(fn(*args)),),
  File "/home/gary/.local/share/virtualenvs/tensorflow_test-5pQI_zfB/lib/python3.10/site-packages/torch/nn/modules/module.py", line 389, in _forward_unimplemented
    _version: int = 1
NotImplementedError: Module [YOLO] is missing the required "forward" function

**Comment by glenn-jocher** [comment]
@ofirgo I think you would typically train a YOLO model normally using the Ultralytics package before selecting an export destination like MCT:


For example, first run `pip install ultralytics`, and then to train a new model:

```python
from ultralytics import YOLO

# Load a YOLOv8 model
model = YOLO("yolov8n.pt")

# Train the model
results = model.train(data="coco8.yaml", epochs=10)
```

For more details please visit https://docs.ultralytics.com/modes/train.

**Comment by t56gary** [comment]
> @ofirgo I think you would typically train a YOLO model normally using the Ultralytics package before selecting an export destination like MCT. For example, first run `pip install ultralytics`, and then to train a new model:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load a YOLOv8 model
> model = YOLO("yolov8n.pt")
> 
> # Train the model
> results = model.train(data="coco8.yaml", epochs=10)
> ```
> 
> For more details please visit https://docs.ultralytics.com/modes/train.

I have successfully trained a custom YOLOv8 model using the Ultralytics package. I encountered no issues during the training process.
I encounter an error when I use the MCT tool to quantize the model, as shown in the code I pasted.
I am trying to use Model Compression Toolkit (MCT) to quantize my model and then convert it with Uni-PyTorch in order to deploy it on the IMX500, similar to the SSDMobileNetV2 model I tested previously.

**Comment by Idan-BenAmi** [comment]
Hi @t56gary ,

Assuming you have your custom YOLOv8 model trained,

The Ultralytics YOLOv8 model requires some adjustments before applying MCT (as mentioned in our tutorial). These adjustments include ensuring torch.FX compatibility (required by MCT) and some modifications to the detection head to enhance quantization accuracy. The error you encountered is related to a torch.fx compatibility issue.

You can use our adjusted model from the tutorial as a reference for the required adjustments - [here](https://github.com/sony/model_optimization/blob/main/tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py).

Alternatively, you might be able to use our adjusted model and load your new weights (I'll add example code below), but please note that this tutorial and reference model are aimed to example inference on COCO dataset and therefore you might need to modify it for your custom dataset. 

# Create new "adjusted" model
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import yolov8_pytorch
model, cfg_dict = yolov8_pytorch("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml")

# Load your new weights into the model
model.load_state_dict(...)
model.eval()

# The model is ready to apply MCT

Good luck
Idan

**Comment by t56gary** [comment]
Hi @Idan-BenAmi,

Thank you for the response.

I tried the method you provided, but my model weight is missing two keys: "model.22.strides" and "model.22.anchor." Additionally, the various torch.sizes of my weights are not compatible with the model weight in the mct_model_garden.

It seems that I need to retrain the model using mct_model_garden instead of using Ultralytics. Is there a script for training a model in the mct_model_garden repository?

I don't know if my idea is correct or not. If you have any better ideas, please let me know.

**Comment by Idan-BenAmi** [comment]
Hi @t56gary ,
I think the typical flow is the previous flow you've tried. have you modified any parameter in your custom model which isn't compatible with COCO dataset? this might explain the size compatibility issue.
Hope it helps.
Idan

**Comment by Idan-BenAmi** [comment]
Hi @t56gary, we are closing this issue due to a lack of response. If it remains relevant, please feel free to open a new issue. Thank you!

**Comment by ServiAmirPM** [comment]
I’d like to share that we're collaborating with Ultralytics to simplify model export, offering a much easier way to export Ultralytics models (like **yolov8n**) to IMX500. For more information, please visit
[IMX500 Export for Ultralytics YOLOv8 - Ultralytics YOLO Docs](https://docs.ultralytics.com/integrations/sony-imx500/)

**Comment by ServiAmirPM** [comment]
Hi @mzahana 

Thanks for sharing. It seems like MCT and converter passed successfully, and the error arrives from picamera2 (RaspberryPi library). I would recommend going to Raspberry PI AI Camera forum to get support on that issue. Specifically, I just saw a thread with the same error raised by another user - https://forums.raspberrypi.com/viewtopic.php?t=379553

**Comment by alexander-sony** [comment]
@ServiAmirPM
There is a problem in the instructions on https://docs.ultralytics.com/integrations/sony-imx500/#what-performance-can-i-expect-from-yolov8-models-on-the-imx500. Specifically the instructions to install picamera2 seems to create issues for the imx500 examples. I suggest removing that instruction until it's been tested with existing imx500 examples in the picamera2 repo.

```
git clone -b next https://github.com/raspberrypi/picamera2
cd picamera2 && pip install -e . --break-system-packages
``` 

If someone already followed the instructions they have to uninstall picamera2 and reinstall using recommended way: `sudo apt install -y python3-picamera2`
