### ISSUE TITLE
Cannot import model_compression_toolkit as mct in Post-Training Quantization Example of MobileNetV2 Keras Model

### ISSUE THREAD

**Issue by camilaodsouza** [sony/model_optimization#1144]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

cannot print version because cannot import 

### OS Platform and Distribution

Running on Google Colab

### Python version

2.1.0

### Describe the issue

Cannot import model_compression_toolkit when running second code cell of Post-Training Quantization Example of MobileNetV2 Keras Model tutorial in Google Colab. Receiving the following error: 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-4-306a47399e1f>](https://localhost:8080/#) in <cell line: 3>()
      1 import tensorflow as tf
      2 import keras
----> 3 import model_compression_toolkit as mct
      4 import os

8 frames
[/usr/local/lib/python3.10/dist-packages/model_compression_toolkit/core/keras/back2framework/keras_model_builder.py](https://localhost:8080/#) in <module>
     23 if version.parse(tf.__version__) >= version.parse("2.13"):
     24     from keras import Input
---> 25     from keras.src.layers.core import TFOpLambda
     26     from keras.src.engine.base_layer import TensorFlowOpLayer, Layer
     27 else:

ImportError: cannot import name 'TFOpLambda' from 'keras.src.layers.core' (/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

PS: tensorflow version installed was 2.17.0 
Tensorflow version needs to be pinned to 2.14

### Expected behaviour

Cell running without errors being raised

### Code to reproduce the issue

```python
Running https://colab.research.google.com/github/sony/model_optimization/blob/main/tutorials/notebooks/imx500_notebooks/keras/example_keras_mobilenetv2_for_imx500.ipynb
```

### Log output

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-4-306a47399e1f>](https://localhost:8080/#) in <cell line: 3>()
      1 import tensorflow as tf
      2 import keras
----> 3 import model_compression_toolkit as mct
      4 import os

8 frames
[/usr/local/lib/python3.10/dist-packages/model_compression_toolkit/core/keras/back2framework/keras_model_builder.py](https://localhost:8080/#) in <module>
     23 if version.parse(tf.__version__) >= version.parse("2.13"):
     24     from keras import Input
---> 25     from keras.src.layers.core import TFOpLambda
     26     from keras.src.engine.base_layer import TensorFlowOpLayer, Layer
     27 else:

ImportError: cannot import name 'TFOpLambda' from 'keras.src.layers.core' (/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by lapid92** [comment]
Hi @camilaodsouza, thank you for raising this issue.
The issue was that Google Colab's default TensorFlow version is 2.17, while MCT supports versions up to 2.15.x. We addressed this in the PR (#1147) by updating the tutorial to install TensorFlow 2.14.
We are currently working on providing an informative message for users attempting to use unsupported TensorFlow versions with MCT.
