### ISSUE TITLE
check if coco/train already exists in Gradient-Based Post Training Quantization code block

### ISSUE THREAD

**Issue by alexander-sony** [sony/model_optimization#1194]
### Issue Type

Performance

### Source

source

### MCT Version

2.2

### Describe the issue

https://github.com/sony/model_optimization/blob/main/tutorials/notebooks/imx500_notebooks/keras/keras_yolov8n_for_imx500.ipynb

see title - assign this to me

### Expected behaviour

see title

### Code to reproduce the issue

```python
see title
```

### Log output

see title

**Comment by ofirgo** [comment]
Hi @alexander-sony, thank you for raising the issue.
I assigned you for it as you requested, if you have any problems feel free to reach out.

I also assigned @Idan-BenAmi since he is responsible for this tutorial.
