### ISSUE TITLE
'DataLoader' object not callable

### ISSUE THREAD

**Issue by freke** [sony/model_optimization#1196]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

Running on Google Colab

### OS Platform and Distribution

Running on Google Colab

### Python version

3.10

### Describe the issue

Error trying to run the example in colab, get the error "'DataLoader' object not callable"
![Screenshot from 2024-08-29 08-51-53](https://github.com/user-attachments/assets/d4dd8f9c-cc07-4176-b105-403310b1cdaa)

### Expected behaviour

To be able to run the example code with out issues.

### Code to reproduce the issue

```python
https://github.com/sony/model_optimization/blob/main/tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_pose_for_imx500.ipynb
```

### Log output

![Screenshot from 2024-08-29 08-51-53](https://github.com/user-attachments/assets/fcf08672-8aca-48fc-b9db-73624a958d6d)

**Comment by alexander-sony** [comment]
for me it seems that the dataloader not created properly, missing the extra step of generator creation, compare with code block setup for post training quantization.
