### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by freke** [sony/model_optimization#1202]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

Running on Google Colab

### OS Platform and Distribution

Running on Google Colab

### Python version

3.10

### Describe the issue

SyntaxError: invalid syntax

pytorch_efficient_anomaly_detection.ipynb
`import tutorials.mct_model_garden.models_pytorch.Efficient_Anomaly_Det.efficient_ad import get_pdn_small, get_autoencoder, UnifiedAnomalyDetectionModel`

### Expected behaviour

To be able to run the example code with out issues.

### Code to reproduce the issue

```python
https://colab.research.google.com/github/sony/model_optimization/blob/main/tutorials/notebooks/imx500_notebooks/pytorch/pytorch_efficient_anomaly_detection.ipynb
```

### Log output

![image](https://github.com/user-attachments/assets/b54d4e27-89d4-4469-9d35-e8fd411c8ae7)

**Comment by Idan-BenAmi** [comment]
Hi @freke ,
Thank you for your feedback. We’re currently enhancing this tutorial to further compress the model, and we’ll provide an update once it’s ready, including a resolution of the issue you reported

Best regards,
Idan

**Comment by Idan-BenAmi** [comment]
Hi @freke, I'm closing this issue as the tutorial is no longer available. We're in the process of updating it and will publish it as soon as it's ready.
Thanks
Idan
