### ISSUE TITLE
How to train YOLov8n and quantize with MCT for IMX500.

### ISSUE THREAD

**Issue by sato-kenryo** [sony/model_optimization#1224]
### Issue Type

Others

### Source

pip (model-compression-toolkit)

### MCT Version

2.2.0

### OS Platform and Distribution

Windows 11 Pro 23H2

### Python version

3.10.12

### Describe the issue

Hi, as I wrote in the title, I want to train YOLOv8n and quantize it using MCT.
I'll use the model on IMX500.

I came up with two methods, referring to the following links.
I would appreciate it if you could tell me which one is possible.

Link: https://github.com/sony/model_optimization/issues/1139

1. Train and quantize YOLOv8n in MCT's model_garden.
2. Train YOLOv8n in Ultralytics and quantize it with MCT.

Below is what I did.

<br>
Regarding 1:<br>
I loaded the YOLOv8n model from MCT_model_garden with the following code.

from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import ModelPyTorch, yaml_load, model_predict
cfg_dict = yaml_load("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml", append_filename=True)  # model dict
model = ModelPyTorch.from_pretrained("SSI-DNN/pytorch_yolov8n_detection_640x640", cfg=cfg_dict)

However, I couldn't find how to train this model.  

<br>
Regarding 2:<br>
First, I trained the YOLOv8n model by referring to the following official Ultralytics website.

Link: https://docs.ultralytics.com/ja/modes/train/#introduction

The specific code is as follows:

```
from ultralytics import YOLO

#Douwnload yolov8n.pt from ultralytics
dlPt = YOLO("yolov8n.pt")

 model_YOLO = YOLO("/content/tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml").load("/content/yolov8n.pt")  # build from YAML and transfer weights
results = dlPt.train(data="coco8.yaml", epochs=10, imgsz=640)
```

This model had been trained successfully.

Next, I tried to quantize model_YOLO, but an error occurred.
Below is the code and a capture of the error.

```
from model_compression_toolkit.core.common.network_editors import NodeNameScopeFilter
from model_compression_toolkit.core import BitWidthConfig
import model_compression_toolkit as mct
from tutorials.mct_model_garden.evaluation_metrics.coco_evaluation import coco_dataset_generator
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8_preprocess import yolov8_preprocess_chw_transpose
from typing import Iterator, Tuple, List

REPRESENTATIVE_DATASET_FOLDER = './coco/val2017/'
REPRESENTATIVE_DATASET_ANNOTATION_FILE = './coco/annotations/instances_val2017.json'
BATCH_SIZE = 4
n_iters = 20

# Load representative dataset
representative_dataset = coco_dataset_generator(dataset_folder=REPRESENTATIVE_DATASET_FOLDER,
                                                annotation_file=REPRESENTATIVE_DATASET_ANNOTATION_FILE,
                                                preprocess=yolov8_preprocess_chw_transpose,
                                                batch_size=BATCH_SIZE)

# Define representative dataset generator
def get_representative_dataset(n_iter: int, dataset_loader: Iterator[Tuple]):
    """
    This function creates a representative dataset generator. The generator yields numpy
        arrays of batches of shape: [Batch, H, W ,C].
    Args:
        n_iter: number of iterations for MCT to calibrate on
    Returns:
        A representative dataset generator
    """
    def representative_dataset() -> Iterator[List]:
        ds_iter = iter(dataset_loader)
        for _ in range(n_iter):
            yield [next(ds_iter)[0]]

    return representative_dataset

# Get representative dataset generator
representative_dataset_gen = get_representative_dataset(n_iter=n_iters,
                                                        dataset_loader=representative_dataset)

# Set IMX500-v3 TPC (extended support in 16b operations)
tpc = mct.get_target_platform_capabilities(fw_name="pytorch",
                                           target_platform_name='imx500',
                                           target_platform_version='v3')

# Configure MCT manually for specific layers
manual_bit_cfg = BitWidthConfig()
manual_bit_cfg.set_manual_activation_bit_width(
    [NodeNameScopeFilter('mul'),
     NodeNameScopeFilter('sub'),
     NodeNameScopeFilter('sub_1'),
     NodeNameScopeFilter('add_6'),
     NodeNameScopeFilter('add_7'),
     NodeNameScopeFilter('stack')], 16)

# Specify the necessary configuration for mixed precision quantization
config = mct.core.CoreConfig(mixed_precision_config=mct.core.MixedPrecisionQuantizationConfig(num_of_images=10),
                             quantization_config=mct.core.QuantizationConfig(concat_threshold_update=True),
                             bit_width_config=manual_bit_cfg)

# Define target Resource Utilization for mixed precision weights quantization (76% of 'standard' 8bits quantization).
# We measure the number of parameters to be 3146176 and calculate the target memory (in Bytes).
resource_utilization = mct.core.ResourceUtilization(weights_memory=3146176 * 0.76)

# Perform post training quantization
quant_model, _ = mct.ptq.pytorch_post_training_quantization(in_module=model_YOLO,
                                                            representative_data_gen=representative_dataset_gen,
                                                            target_resource_utilization=resource_utilization,
                                                            core_config=config,
                                                            target_platform_capabilities=tpc)
print('Quantized model is ready')
```
![スクリーンショット 2024-09-19 114200](https://github.com/user-attachments/assets/4a566e4c-0234-457e-b032-b63a31e22d09)

<br>
In response to this error, I tried to prepare the model for quantization with MCT by referring to the following git issues, but an error occurred.
Below is the code and a capture of the error.

Link: https://github.com/sony/model_optimization/issues/1139

```
# Create new "adjusted" model
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import yolov8_pytorch
model_git, cfg_dict = yolov8_pytorch("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml")
```
![スクリーンショット 2024-09-19 141030](https://github.com/user-attachments/assets/8f671fbd-6068-4bba-90f4-86df3159f6a0)

I would appreciate any help. Thank you.

### Expected behaviour

I can train YOLOv8n and quantize it usin MCT for IMX500.

### Code to reproduce the issue

```python
Link to notebook:
https://colab.research.google.com/drive/1dTilLp7-7Jql36nr7PjjTOJfFAKXjkpe?usp=drive_link


!pip install -q torch
!pip install onnx
!pip install -q pycocotools
!pip install 'huggingface-hub>=0.21.0'
!pip install sony-custom-layers
!pip install model-compression-toolkit
!pip install ultralytics


import sys
import os
import importlib

if not importlib.util.find_spec('model_compression_toolkit'):
    !pip install mct-nightly
!git clone https://github.com/sony/model_optimization.git temp_mct && mv temp_mct/tutorials . && \rm -rf temp_mct
sys.path.insert(0,"tutorials")


if not os.path.isdir('coco'):
    !wget -nc http://images.cocodataset.org/annotations/annotations_trainval2017.zip
    !unzip -q -o annotations_trainval2017.zip -d ./coco
    !echo Done loading annotations
    !wget -nc http://images.cocodataset.org/zips/val2017.zip
    !unzip -q -o val2017.zip -d ./coco
    !echo Done loading val2017 images


import torch
from ultralytics import YOLO
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import ModelPyTorch, yaml_load, model_predict

cfg_dict = yaml_load("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml", append_filename=True)  # model dict
model = ModelPyTorch.from_pretrained("SSI-DNN/pytorch_yolov8n_detection_640x640", cfg=cfg_dict)


from ultralytics import YOLO

# YOLOv8nのモデルをロード
dlPt = YOLO("yolov8n.pt")

# 参考URLを元に、モデルを学習
model_YOLO = YOLO("/content/tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml").load("/content/yolov8n.pt")  # build from YAML and transfer weights
results = model_YOLO.train(data="coco8.yaml", epochs=10)


from model_compression_toolkit.core.common.network_editors import NodeNameScopeFilter
from model_compression_toolkit.core import BitWidthConfig
import model_compression_toolkit as mct
from tutorials.mct_model_garden.evaluation_metrics.coco_evaluation import coco_dataset_generator
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8_preprocess import yolov8_preprocess_chw_transpose
from typing import Iterator, Tuple, List

REPRESENTATIVE_DATASET_FOLDER = './coco/val2017/'
REPRESENTATIVE_DATASET_ANNOTATION_FILE = './coco/annotations/instances_val2017.json'
BATCH_SIZE = 4
n_iters = 20

# Load representative dataset
representative_dataset = coco_dataset_generator(dataset_folder=REPRESENTATIVE_DATASET_FOLDER,
                                                annotation_file=REPRESENTATIVE_DATASET_ANNOTATION_FILE,
                                                preprocess=yolov8_preprocess_chw_transpose,
                                                batch_size=BATCH_SIZE)

# Define representative dataset generator
def get_representative_dataset(n_iter: int, dataset_loader: Iterator[Tuple]):
    """
    This function creates a representative dataset generator. The generator yields numpy
        arrays of batches of shape: [Batch, H, W ,C].
    Args:
        n_iter: number of iterations for MCT to calibrate on
    Returns:
        A representative dataset generator
    """
    def representative_dataset() -> Iterator[List]:
        ds_iter = iter(dataset_loader)
        for _ in range(n_iter):
            yield [next(ds_iter)[0]]

    return representative_dataset

# Get representative dataset generator
representative_dataset_gen = get_representative_dataset(n_iter=n_iters,
                                                        dataset_loader=representative_dataset)

# Set IMX500-v3 TPC (extended support in 16b operations)
tpc = mct.get_target_platform_capabilities(fw_name="pytorch",
                                           target_platform_name='imx500',
                                           target_platform_version='v3')

# Configure MCT manually for specific layers
manual_bit_cfg = BitWidthConfig()
manual_bit_cfg.set_manual_activation_bit_width(
    [NodeNameScopeFilter('mul'),
     NodeNameScopeFilter('sub'),
     NodeNameScopeFilter('sub_1'),
     NodeNameScopeFilter('add_6'),
     NodeNameScopeFilter('add_7'),
     NodeNameScopeFilter('stack')], 16)

# Specify the necessary configuration for mixed precision quantization
config = mct.core.CoreConfig(mixed_precision_config=mct.core.MixedPrecisionQuantizationConfig(num_of_images=10),
                             quantization_config=mct.core.QuantizationConfig(concat_threshold_update=True),
                             bit_width_config=manual_bit_cfg)

# Define target Resource Utilization for mixed precision weights quantization (76% of 'standard' 8bits quantization).
# We measure the number of parameters to be 3146176 and calculate the target memory (in Bytes).
resource_utilization = mct.core.ResourceUtilization(weights_memory=3146176 * 0.76)

# Perform post training quantization
quant_model, _ = mct.ptq.pytorch_post_training_quantization(in_module=model_YOLO,
                                                            representative_data_gen=representative_dataset_gen,
                                                            target_resource_utilization=resource_utilization,
                                                            core_config=config,
                                                            target_platform_capabilities=tpc)
print('Quantized model is ready')


# Create new "adjusted" model
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import yolov8_pytorch
model_git, cfg_dict = yolov8_pytorch("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml")

# Load your new weights into the model
model_git.load_state_dict("/content/yolov8n.pt")

model.load_state_dict(torch.load('/content/yolov8n.pt'))
```

### Log output

error at 
```
quant_model, _ = mct.ptq.pytorch_post_training_quantization(in_module=model_YOLO,
                                                            representative_data_gen=representative_dataset_gen,
                                                            target_resource_utilization=resource_utilization,
                                                            core_config=config,
                                                            target_platform_capabilities=tpc)
```

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-21-126d9bbc31e0>](https://localhost:8080/#) in <cell line: 66>()
     64 
     65 # Perform post training quantization
---> 66 quant_model, _ = mct.ptq.pytorch_post_training_quantization(in_module=model_YOLO,
     67                                                             representative_data_gen=representative_dataset_gen,
     68                                                             target_resource_utilization=resource_utilization,

23 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in __getstate__(self)
    651         # to a separate thread and then just sharing the data queue
    652         # but signalling the end is tricky without a non-blocking API
--> 653         raise NotImplementedError("{} cannot be pickled", self.__class__.__name__)
    654 
    655 

NotImplementedError: ('{} cannot be pickled', '_SingleProcessDataLoaderIter')

<br>
error at

```
# Load your new weights into the model
model_git.load_state_dict("/content/yolov8n.pt")
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-19-4263568c4f83>](https://localhost:8080/#) in <cell line: 2>()
      1 # Load your new weights into the model
----> 2 model_git.load_state_dict("/content/yolov8n.pt")

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict, assign)
   2164         """
   2165         if not isinstance(state_dict, Mapping):
-> 2166             raise TypeError(f"Expected state_dict to be dict-like, got {type(state_dict)}.")
   2167 
   2168         missing_keys: List[str] = []

TypeError: Expected state_dict to be dict-like, got <class 'str'>.

<br>
error at
`model.load_state_dict(torch.load('/content/yolov8n.pt'))`

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-92-dc6a9b1eae46> in <cell line: 1>()
----> 1 model.load_state_dict(torch.load('/content/yolov8n.pt'))

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict, assign)
   2213 
   2214         if len(error_msgs) > 0:
-> 2215             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2216                                self.__class__.__name__, "\n\t".join(error_msgs)))
   2217         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for ModelPyTorch:
	Missing key(s) in state_dict: "model.0.conv.weight", "model.0.bn.weight", "model.0.bn.bias", "model.0.bn.running_mean", "model.0.bn.running_var", "model.1.conv.weight", "model.1.bn.weight", "model.1.bn.bias", "model.1.bn.running_mean", "model.1.bn.running_var", "model.2.cv1.conv.weight", "model.2.cv1.bn.weight", "model.2.cv1.bn.bias", "model.2.cv1.bn.running_mean", "model.2.cv1.bn.running_var", "model.2.cv2.conv.weight", "model.2.cv2.bn.weight", "model.2.cv2.bn.bias", "model.2.cv2.bn.running_mean", "model.2.cv2.bn.running_var", "model.2.m.0.cv1.conv.weight", "model.2.m.0.cv1.bn.weight", "model.2.m.0.cv1.bn.bias", "model.2.m.0.cv1.bn.running_mean", "model.2.m.0.cv1.bn.running_var", "model.2.m.0.cv2.conv.weight", "model.2.m.0.cv2.bn.weight", "model.2.m.0.cv2.bn.bias", "model.2.m.0.cv2.bn.running_mean", "model.2.m.0.cv2.bn.running_var", "model.3.conv.weight", "model.3.bn.weight", "model.3.bn.bias", "model.3.bn.running_mean", "model.3.bn.running_var", "model.4.cv1.conv.weight", "model.4.cv1.bn.weight", "model.4.cv1.bn.bias", "model.4.cv1.bn.running_mean", "model.4.cv1.bn.running_var", "model.4.cv2.conv.weight", "model.4.cv2.bn.weight", "model.4.cv2.bn.bias", "model.4.cv2.bn.running_mean", "model.4.cv2.bn.running_var", "model.4.m.0.cv1.conv.weight", "model.4.m.0.cv1.bn.weight", "model.4.m.0.cv1.bn.bias", "model.4.m.0.cv1.bn.running_mean", "model.4.m.0.cv1.bn.running_var", "model.4.m.0.cv2.conv.weight", "model.4.m.0.cv2.bn.weight", "model.4.m.0.cv2.bn.bias", "model.4.m.0.cv2.bn...
	Unexpected key(s) in state_dict: "date", "version", "license", "docs", "epoch", "best_fitness", "model", "ema", "updates", "optimizer", "train_args".

**Comment by DaniAffCH** [comment]
Hi, I’d like to follow up on this discussion as I’m encountering a similar issue. I need to convert Ultralytics YOLO into MCT-style YOLO. Is that feasible?

I attempted to export the state_dict from Ultralytics YOLO to MCT YOLO using the following code:

``` python
ultralytics_model = YOLO("yolov8n.pt")
model.load_state_dict(ultralytics_model.model.state_dict())
```

However, I received the following error:
```bash
RuntimeError: Error(s) in loading state_dict for ModelPyTorch:
	Missing key(s) in state_dict: "model.22.anchors", "model.22.strides".
```

Are these additional trainable parameters? If they are not, how can I integrate them from the Ultralytics model?

**Comment by Idan-BenAmi** [comment]
Hello @sato-kenryo and @DaniAffCH,
Thank you for your feedback.
In order to train yolov8n model and quantize it using MCT you need to first train the model in Ultralytics. Once you have the "yolov8n.pt" file, you can use our tutorial and replace the relevant section ("Download a Pre-Trained Model") with the following: 

```
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import yolov8_pytorch, model_predict

# Load the YOLOv8 for MCT (adjusted model)
model, cfg_dict = yolov8_pytorch("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml")

# Load your weights
PRETRAINED_WEIGHTS_FILE = 'yolov8n.pt'
pretrained_weights = torch.load(PRETRAINED_WEIGHTS_FILE)['model'].state_dict()
model.load_state_dict(pretrained_weights, strict=False)

# Set the model to evaluation mode
model.eval()
```

Please be noted that we only checked it with the models from "https://github.com/ultralytics/ultralytics". Therefore, if you changed the model configuration (yolov8n.yaml), it might require modification in the "yolov8_pytorch", the adjusted model for MCT.
The "strides" and "anchors" are constants in the adjusted model, however only match input resolution of 640x640.

**Comment by sato-kenryo** [comment]
Thank you for your comment.

I tried loading the model by the method you suggested and it was successful.
```
from tutorials.mct_model_garden.models_pytorch.yolov8.yolov8 import yolov8_pytorch, model_predict

# Load the YOLOv8 for MCT (adjusted model)
model, cfg_dict = yolov8_pytorch("tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml")

# Load your weights
PRETRAINED_WEIGHTS_FILE = 'yolov8n.pt'
pretrained_weights = torch.load(PRETRAINED_WEIGHTS_FILE)['model'].state_dict()
model.load_state_dict(pretrained_weights, strict=False)

# Set the model to evaluation mode
model.train()
```


However, I can't find how to train the model after that.

When I tried the tutorial on the Ultralytics website, I got the following error.

```
# 参考URLを元に、YOLOライブラリを使ってモデルを学習
#ultralytics URL: https://docs.ultralytics.com/ja/modes/train/#key-features-of-train-mode

results = model.train(data="coco8.yaml", epochs=10)
```
![image](https://github.com/user-attachments/assets/54b5a3e2-d9bb-406c-96f9-b2b80a78c76c)

How can I train the loaded yolov8n?

**Comment by Idan-BenAmi** [comment]
Hi @sato-kenryo,
Loading the model with the above method should be done after training the model. 
You will first need to work in Ultralytics and train the yolov8n model, next you may try the method above in order to make the model compatible with MCT.

**Comment by sato-kenryo** [comment]
I appreciate your support. 
Thanks to you, I was able to train the model appropriately.

**Comment by ServiAmirPM** [comment]
Update:
To make the deployment process more easy and accessible across a range of tasks, we’re collaborating with Ultralytics to simplify model export. This integration will replace our tutorials and example models you mentioned, offering a much easier way to export Ultralytics models to our device. Additionally, it allows you to re-train the model on your custom dataset before exporting. For more information, please visit
[IMX500 Export for Ultralytics YOLOv8 - Ultralytics YOLO Docs](https://docs.ultralytics.com/integrations/sony-imx500/)

Thanks
