### ISSUE TITLE
Yolov8 SDSP Compatibility

### ISSUE THREAD

**Issue by DaniAffCH** [sony/model_optimization#1236]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

2.2.0

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10.12

### Describe the issue

After recent changes, the yolov8 model obtained using the tutorial is no longer compatible with SDSP.
I have a quantized version of yolov8 obtained using the tutorial of [mct 2.1.0](https://github.com/sony/model_optimization/blob/9d3593f8b4707e613fcdf498ad948820032baa0d/tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb) and that is fully compatible with SDSP 3.14.
However, when I follow the [current tutorial](https://github.com/sony/model_optimization/blob/bb24123e3b8e2c2a89636b6d2d0a928f890333b5/tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb) SDSP raises an error (reported in the log output section).

I tried to compare the computational graphs of the model obtained using mct 2.1.0 and mct 2.2.0. The two graphs differ exactly in the layers highlighted in the SDSP error log.

For instance, consider the error:

```
Node [ONNX] op: WeightsPOTQuantizer, id: /model/mul/WeightsPOTQuantizer, errors:
	Output error - output index: 0, output tensor/node: quantized data, reason: WeightsPOTQuantizer output can't be connected to Mul
```

These are the related graph nodes of the model coming from mct 2.1.0

![](https://github.com/user-attachments/assets/e01e9f4b-0436-4677-ad82-eaf43146dcf9)

Whereas this is the same portion of graph from mct 2.2.0

![](https://github.com/user-attachments/assets/f095eae8-1d70-4c61-9eb1-b55626470c6e)

### Code to reproduce the issue

1. Run the [current tutorial](https://github.com/sony/model_optimization/blob/bb24123e3b8e2c2a89636b6d2d0a928f890333b5/tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb)

2. Run the following command with SDSP 3.14 `uni-pytorch -i qmodel_pp.onnx -o uni_model`

### Log output

```
2024-10-01 09:58:41,593 INFO : Running version 1.10.0 
2024-10-01 09:58:41,593 INFO : Converting qmodel_pp.onnx
2024-10-01 09:58:53,146 ERROR : CODE: [INVOP] The network is not aligned with SDSP converter's restrictions. Errors are:
Node [ONNX] op: WeightsPOTQuantizer, id: /model/mul/WeightsPOTQuantizer, errors:
	Output error - output index: 0, output tensor/node: quantized data, reason: WeightsPOTQuantizer output can't be connected to Mul
--------------------------------------------------
Node [ONNX] op: WeightsPOTQuantizer, id: /model/sub/WeightsPOTQuantizer, errors:
	Output error - output index: 0, output tensor/node: quantized data, reason: WeightsPOTQuantizer output can't be connected to Sub
--------------------------------------------------
Node [ONNX] op: WeightsPOTQuantizer, id: /model/sub_1/WeightsPOTQuantizer, errors:
	Output error - output index: 0, output tensor/node: quantized data, reason: WeightsPOTQuantizer output can't be connected to Sub

```

**Comment by DaniAffCH** [comment]
Hi, I would like to kindly follow up on this issue. I am looking to quantize a custom YOLOv8n model. Since the issue occurs in three specific layers, is there a way to exclude these layers from the quantization process, keeping them in FP32, while quantizing the rest of the model?

**Comment by ServiAmirPM** [comment]
Hi Dani

The issue you are facing is due to the usage of a capability that is supported by converter version 3.14.2 (and not supported by 3.14.0)
Specifically, utilizing 16bit quantization capabilities.

I would recommend you use the 3.14.2 converter version once it's available for you.

**Comment by DaniAffCH** [comment]
Hi @ServiAmirPM 

I appreciate your support. I just tried with SDSP `3.15.3` and everything went smoothly.
I'll close this issue then.
