### ISSUE TITLE
No solution was found during solving the LP problem

### ISSUE THREAD

**Issue by Saalsifis** [sony/model_optimization#1269]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

2.1.1

### OS Platform and Distribution

Ubuntu 24.04.1 LTS

### Python version

3.9.20

### Describe the issue

When I export my model to imx format I get the error "No solution was found during solving the LP problem". I tried to train it agian with only 1 epoch and it works, but when I train it with more epochs I always get this error.

This is my environement:

Ultralytics 8.3.31 🚀 Python-3.9.20 torch-2.5.1+cu124 CUDA:0 (NVIDIA RTX A4000, 16376MiB)

### Expected behaviour

Model exported in rpk format

### Code to reproduce the issue

```python
from ultralytics import YOLO
model = YOLO("runs/detect/train/weights/best.pt")
model.export(format="imx",device=0)

# model trained with the following code:
#from ultralytics import YOLO
#model = YOLO("yolov8s.pt")
#model.train(data="data.yaml",device=0) # data comes from roboflow, exported as yolov8 format
```

### Log output

CRITICAL:Model Compression Toolkit:No solution was found during solving the LP problem                               IMX: export failure ❌ 285.5s: No solution was found during solving the LP problem                                   Traceback (most recent call last):                                                                                     File "<stdin>", line 1, in <module>                                                                                  File "/home/oui/trainer/lib/python3.9/site-packages/ultralytics/engine/model.py", line 734, in export             return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)                                       File "/home/oui/trainer/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 384, in __call__        f[13], _ = self.export_imx()                                                                                       File "/home/oui/trainer/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 147, in outer_func      raise e                                                                                                            File "/home/oui/trainer/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func      f, model = inner_func(*args, **kwargs)                                                                             File "/home/oui/trainer/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 1158, in export_imx     else mct.ptq.pytorch_post_training_quantization(  # Perform post training quantization                             File "/home/oui/trainer/lib/python3.9/site-packages/model_compression_toolkit/ptq/pytorch/quantization_facade.py", line 112, in pytorch_post_training_quantization                                                                     tg, bit_widths_config, _ = core_runner(in_model=in_module,                                                         File "/home/oui/trainer/lib/python3.9/site-packages/model_compression_toolkit/core/runner.py", line 133, in core_runner                                                                                                                bit_widths_config = search_bit_width(tg,                                                                           File "/home/oui/trainer/lib/python3.9/site-packages/model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py", line 126, in search_bit_width                                                             result_bit_cfg = search_method_fn(search_manager,                                                                  File "/home/oui/trainer/lib/python3.9/site-packages/model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py", line 74, in mp_integer_programming_search                                             assert lp_problem.status == LpStatusOptimal, Logger.critical(                                                      File "/home/oui/trainer/lib/python3.9/site-packages/model_compression_toolkit/logger.py", line 117, in critical                                                                                                                        raise Exception(msg)                                                                                             Exception: No solution was found during solving the LP problem

**Comment by ofirgo** [comment]
Hi @Saalsifis,

This error usually happens when trying to compress the model to a target memory that is too small for the lowest possible bit-width representation available on the IMX500.
So, this might be an issue with your call to MCT.
Can you please provide the code that you use to run MCT?
Also, what target memory are you providing for the model compression?

I didn't completely understand your comment regarding the retraining that makes the model work, so if you can explain exactly what you did there to make it work, it might help us understand the issue.

Thanks,
Ofir

**Comment by Idan-BenAmi** [comment]
Hi @Saalsifis ,
Thanks for rising this issue.
can you specify the yolov8 configuration you're trying to export? is it yolov8n, yolov8s or other configuration?
Thanks
Idan

**Comment by Saalsifis** [comment]
Hi, I tried yolov8n and yolov8s, the bug happened with both and the dataset comes from https://universe.roboflow.com/mohamed-traore-2ekkp/ppe-detection-l80fg/dataset/5

**Comment by Idan-BenAmi** [comment]
Hi @Saalsifis ,

Can you please share the console output of your code execution ?
It should include details such as the model size, input shape, and more relevant information.

Thanks

**Comment by Saalsifis** [comment]
Hi,

This is the console output:
[log.txt](https://github.com/user-attachments/files/17799514/log.txt)

This is the code I used to train the model:
`from ultralytics import YOLO
model = YOLO("yolov8s.pt")
model.train(data="data.yaml",device=0) # data comes from roboflow, exported as yolov8 format`

However I found out there is a data arg in the export function. So now I try to export with this line:
`model.export(format="imx",device=0,data="data.yaml")`

But now I have issues with numpy, with the default configuration (numpy 1.23, last compatible with tensorflow) I get:
ModuleNotFoundError: No module named 'numpy._core'

**Comment by Saalsifis** [comment]
Hi, so I trained another model with yolov8n.pt, now I can export it using this command:
`model.export(format="imx",device=0)`

But the model generated is bad, it can't detect anything, so I tried exporting it using:
`model.export(format="imx",device=0,data="data.yaml")`

but then again i get the error:
ModuleNotFoundError: No module named 'numpy._core'

I'm using numpy version 1.23 which seems to be the only compatible version as MCT needs >1.22 and Tensorflow needs <1.24
[log.txt](https://github.com/user-attachments/files/17845762/log.txt)
