### ISSUE TITLE
Will MCT support int8 quantization?

### ISSUE THREAD

**Issue by Mukulareddy** [sony/model_optimization#273]
Hello
I am trying out MCT using int8 quantization. But i couldn't find any provision in the repo for int8 quantization.
Kindly comment if any one has tried this.

Thanks

**Comment by Mukulareddy** [comment]
Hello,
Thanks for your comments. 
I am trying to quantize a model using MCT. After i quantize, the resulting model is in float 32 data type. I would want the model in int8 data type so that the model size is reduced. Can i do it using MCT is my question. 

It would be great & helpful if you could elaborate on the MCT fake quantization.

**Comment by ofirgo** [comment]
Hi @Mukulareddy,
Thank you for the question.
What you're looking for is currently not supported in our MCT, but we will take your feedback as feature request and will address it hopefully in future updates.

Regarding the fake quantization - MCT stores the quantized parameters after they've been quantized using a method similar to the one presented in the following link: [tf/quantization/fake_quant_with_min_max_vars_per_channel](https://www.tensorflow.org/api_docs/python/tf/quantization/fake_quant_with_min_max_vars_per_channel).
That is, the parameters are quantized and stored in float32 data type.

If I understand correctly, you are referring to something more similar to this technique: [tf/quantization/quantize](https://www.tensorflow.org/api_docs/python/tf/quantization/quantize),
where a specific dtype can be provided through the parameter `T`.
As I mentioned, this type of quantization is currently not supported in MCT, but we will consider this for future updates.

**Comment by reuvenperetz** [comment]
Hi @Mukulareddy ,
A new method for exporting TFLite int8 models from MCT has recently been added and will be available in the upcoming release.
Please keep in mind that this is an experimental feature and is subject to future changes.

You can find more information and usage example [here](https://github.com/sony/model_optimization/tree/main/model_compression_toolkit/exporter).
If you have any questions or issues, please let us know.
