### ISSUE TITLE
Exception: Trying to quantize node argmax activation of type <dtype: 'float64'> which is not supported, expected type float32

### ISSUE THREAD

**Issue by praveenkumar66d** [sony/model_optimization#489]
### Issue Type

Bug

### Source

source

### MCT Version

1.6.0

### OS Platform and Distribution

linux

### Python version

3.9

### Describe the issue

```shell

As a part of the requirement, we have implemented a keras lambda layer which returns a float64 tensor.
We want to check whether MCT supports float64 format. We are facing the below error.

Error:
Exception: Trying to quantize node argmax activation of type <dtype: 'float64'> which is not supported, expected type float32
```

### Expected behaviour

```shell
To support MCT conversion for float64 model.
```

### Code to reproduce the issue

```shell
N/A
```

### Log output

```shell
Exception: Trying to quantize node argmax activation of type <dtype: 'float64'> which is not supported, expected type float32
```

**Comment by eladc-git** [comment]
Hello @praveenkumar66d,

We have just merged a fix for the issue you reported. You can now use the latest nightly build of MCT (pip install mct-nightly) to try out the fix and confirm that it resolves the problem. Let us know if you have any other issues or if it does not fully resolve the problem.
