### ISSUE TITLE
numpy >= 1.24 support

### ISSUE THREAD

**Issue by Chizkiyahu** [sony/model_optimization#569]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

1.7.1

### OS Platform and Distribution

mac

### Python version

3.9

### Describe the issue

```shell
np.float is not supported in numpy 1.24
```

### Code to reproduce the issue

```shell
running mct with numpy 1.24
```

**Comment by eladc-git** [comment]
Hi @Chizkiyahu, thanks for using MCT.
In NUMPY v1.24 the dtype changes from np.float to np.float32. (also np.int->np.int32).
MCT v1.7.1 supports NUMPY version below 1.24. 
So you can try to downgrade NUMPY to version  below v1.24 or get the nightly version which supports NUMPY v1.24.
Shortly, we about to release new version of MCT which supports NUMPY v1.24 as well.
If you have any other issue don't hesitate.
