### ISSUE TITLE
Does not work on system with multiple CUDA devices

### ISSUE THREAD

**Issue by V0XNIHILI** [sony/model_optimization#613]
### Issue Type

Bug

### Source

pip (mct-nightly)

### MCT Version

1.8.0.28022023.post417

### Python version

3.10.9

### Describe the issue

When moving model to another CUDA device than `cuda:0` (i.e. `cuda:3`), PyTorch starts complaining about various mismatches in tensor locations for operations while performing `mct.pytorch_quantization_aware_training_init(...)`.

### Expected behaviour

Nothing!

For now, my solution is the following:

```python
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "3"
```

Maybe would be good to either fix this in the good or alert users to do the above when having a system with multiple GPUs.

### Code to reproduce the issue

https://github.com/sony/model_optimization/blob/main/tutorials/example_pytorch_qat.py but replace `"cuda"` in line 120 with `"cuda:3"`.

**Comment by ofirgo** [comment]
Hi @V0XNIHILI ,

Sorry for the late response. 
This is a known issue, we are working on fixing it to enable working with a requested GPU.

**Comment by V0XNIHILI** [comment]
Looking forward to a fix!
