### ISSUE TITLE
"python setup.py install" fails installing dependencies (v1.8.0)

### ISSUE THREAD

**Issue by alexander-sony** [sony/model_optimization#681]
### Issue Type

Bug

### Source

source

### MCT Version

1.8.0

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8.10

### Describe the issue

```shell
Followed the instructions from README.md to install mct from source but failed.

Initially tried `(venv)$ python setup.py install` from branch main (8bdde0064). But got error:

Traceback (most recent call last):
  File "setup.py", line 41, in <module>
...
  File "/home/l1000323954/Temp/model_optimization/model_compression_toolkit/target_platform_capabilities/target_platform/op_quantization_config.py", line 19, in <module>
    from mct_quantizers import QuantizationMethod
ModuleNotFoundError: No module named 'mct_quantizers'
```

So instead tried `git checkout 1.8.0` and new try with `(venv)$ python setup.py install`. Error:
```
Reading READEME File
Reading install requirements
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
...
  File "/home/l1000323954/Temp/model_optimization/model_compression_toolkit/core/common/quantization/quantization_params_generation/power_of_two_selection.py", line 15, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
So, for some reason it fails to execute the requirements.txt.
At this moment I install mct simply with `(venv)$ pip install -r requirements.txt`
```


### Expected behaviour

_No response_

### Code to reproduce the issue

```shell
see 'Describe the issue'
```

### Log output

```shell
see 'Describe the issue'
```

**Comment by ofirgo** [comment]
Hello @alexander-sony,
Thank you for bringing this issue to our attention.

I'm trying to reproduce your issue, but I am currently unable to do so.
In the meanwhile, can you please provide the following information:
Do you get an error when installing MCT with `pip install -r requirements.txt`, or is that working fine for you?
Did you try to run `pip install --upgrade pip` before trying to install the setup.py script?

**Comment by ofirgo** [comment]
> Hello @alexander-sony, Thank you for bringing this issue to our attention.
> 
> I'm trying to reproduce your issue, but I am currently unable to do so. In the meanwhile, can you please provide the following information: Do you get an error when installing MCT with `pip install -r requirements.txt`, or is that working fine for you? Did you try to run `pip install --upgrade pip` before trying to install the setup.py script?

Ok, I was able to reproduce your issue, and it seems that there is a problem with installing the package from source.
If you want to install the model-compression-toolkit package (v1.8.0), a good workaround is to install it via PyPi: `pip install model-compression-toolkit`.
If you just want to setup your environment and work on the source code then `pip install -r requirements.txt` as you mentioned you tried should work fine. 

Let me know if you're still getting issues with any of those workarounds.
