### ISSUE TITLE
Error while quantizing PyTorch 

### ISSUE THREAD

**Issue by Mukulareddy** [sony/model_optimization#827]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

1.9.1

### OS Platform and Distribution

ubuntu 20

### Python version

3.8

### Describe the issue

```shell
Facing the below issue when trying to quantize YoloX-tiny model from https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth.
```

### Expected behaviour

```shell
I am trying with python 3.8 and Pytorch version 2.0. As per the latest MCT documentation, MCT should be working.
```

### Code to reproduce the issue

```shell
NA
```

### Log output

```shell
File "/home/user1/envs/mct_torch/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/user1/envs/mct_torch/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 467, in call_module
    ret_val = forward(*args, **kwargs)
  File "/home/user1/envs/mct_torch/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/user1/envs/mct_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/hdd/mukula_STS/SOW6.4/october/YOLOX/yolox/models/yolo_head.py", line 211, in forward
    return self.decode_outputs(outputs, dtype=xin[0].type())
  File "/hdd/mukula_STS/SOW6.4/october/YOLOX/yolox/models/yolo_head.py", line 239, in decode_outputs
    yv, xv = meshgrid([torch.arange(hsize), torch.arange(wsize)])
TypeError: arange(): argument 'end' (position 1) must be Number, not Proxy
```

**Comment by lior-dikstein** [comment]
Hi,
Thank you for bringing this issue to our attention. I'd like to note that our project only supports PyTorch models that can be converted to the torch.fx format. The [torch.fx](https://pytorch.org/docs/stable/fx.html) toolkit offers a static graph representation essential for various model compression techniques, such as batch norm folding.
Unlike classification models, like the ones commonly found in the torchvision library, object detection models often require some manipulation to be converted to torch.fx. For guidance on converting object detection models to the torch.fx format, please refer to our tutorials section: [Ultralytics Library Tutorial](https://github.com/sony/model_optimization/tree/main/tutorials/quick_start/pytorch_fw/ultralytics_lib).

**Comment by Mukulareddy** [comment]
Hello @lior-dikstein ,
Thank you so much for the support.
I have tried with converting yolox-tiny model to torch.fx format by following the steps mentioned in [Ultralytics Library Tutorial](https://github.com/sony/model_optimization/tree/main/tutorials/quick_start/pytorch_fw/ultralytics_lib). But i am facing some import issues like "ModuleNotFoundError: No module named 'common'". Do i need to make any changes in the script apart from what is mentioned in the tutorial to convert yolox-tiny to torch.fx format?
