### ISSUE TITLE
Error while quantizing a PyTorch model

### ISSUE THREAD

**Issue by Mukulareddy** [sony/model_optimization#860]
Hello @lior-dikstein ,
Thank you so much for the support.
I have tried with converting yolox-tiny model to torch.fx format by following the steps mentioned in [Ultralytics Library Tutorial](https://github.com/sony/model_optimization/tree/main/tutorials/quick_start/pytorch_fw/ultralytics_lib). But i am facing some import issues like "ModuleNotFoundError: No module named 'common'". Do i need to make any changes in the script apart from what is mentioned in the tutorial to convert yolox-tiny to torch.fx format?

_Originally posted by @Mukulareddy in https://github.com/sony/model_optimization/issues/827#issuecomment-1815789157_

**Comment by Idan-BenAmi** [comment]
Hi @Mukulareddy .
Thank you for your feedback. 
Typically, each model or each model library (like Ultralytics for example) requires different conversion operations for torch.fx. Therefore it's very likely that you will need some modifications for the Ultralytics tutorial you mentioned. 
Can you share the complete error message you encountered, so I could try to provide you more concrete information?
Thanks
Idan

**Comment by Mukulareddy** [comment]
Hello @Idan-BenAmi ,
I am able to solve the errors i was facing by upgrading the MCT version to 1.10.0.
But when i tried converting YoloX-Tiny PyTorch model from https://github.com/MegEngine/YOLOX/tree/main , i have faced the below error: 
**Exception: Unknown torchvision model name yolox-tiny, Please check available models in https://pytorch.org/vision/stable/models.html**
I am just curious to know if MCT supports conversion of YoloX-Tiny(416x416) model?

**Comment by Idan-BenAmi** [comment]
Hi @Mukulareddy,
YoloX-Tiny is not part of torchvision models library. So using our "quick start" project requires additional support. 
I believe that YoloX-Tiny is compatible with MCT but unfortunately we don't have a tutorial that demonstrates it. Therefore I can't provide you the exact operations required for this model (similar to those outlined in the [Ultralytics example](https://github.com/sony/model_optimization/tree/main/tutorials/quick_start/pytorch_fw/ultralytics_lib).
Typically, adapting such a model for MCT requires minor modifications to support torch.fx conversion, and possibly relocating the post-processing part (bounding box decoding and NMS) out from the model to maintain the performance of the quantized model.
We will consider to add YoloX-Tiny to MCT "quick start" in the future.
Thanks
Idan
