### ISSUE TITLE
[Tutorials] Keras model export

### ISSUE THREAD

**Issue by alexander-sony** [sony/model_optimization#875]
### Issue Type

Documentation

### Source

pip (model-compression-toolkit)

### MCT Version

1.10.0

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.10.12

### Describe the issue

Tutorials normally use `mct.exporter.keras_export_model(...)` for export, see for example https://github.com/sony/model_optimization/blob/main/tutorials/notebooks/example_keras_imagenet.ipynb. This can provide issues for tools/converters/compilers further down the pipeline. It should be considered to document that `quantized_model.save()` is also a valid export method for quantized keras models. Maybe also add explanaition for when to use one or the other.

### Code to reproduce the issue

```shell
see above
```

**Comment by Idan-BenAmi** [comment]
Hi @alexander-sony,
Thank you for your input. We are currently addressing the issue.
Idan

**Comment by reuvenperetz** [comment]
Will be resolved by #879
