### ISSUE TITLE
Exception: Unknown Keras Applications model class resnet50.ResNet50

### ISSUE THREAD

**Issue by Ming-Ivy** [sony/model_optimization#939]
### Issue Type

Bug

### Source

source

### MCT Version

1.11.0

### Python version

3.8.10

### Describe the issue

```shell
when I try to use ths model in model_library keras_applications in main.py: python main.py --model_name resnet50.ResNet50 --model_library keras_applications --validation_dataset_folder /data1/work/Ming/MCT/dataset/imagenet/ILSVRC2012_img_val/ --representative_dataset_folder /data1/work/Ming/MCT/dataset/imagenet/ILSVRC2012_img_test_v10102019/
the error occurs 

Traceback (most recent call last):
  File "main.py", line 131, in <module>
    float_acc, quant_acc, quant_info, dataset_info = quantization_flow(config)
  File "main.py", line 94, in quantization_flow
    ml = model_lib.ModelLib(config)
  File "/data1/work/Ming/MCT/model_optimization/tutorials/quick_start/keras_fw/keras_applications/model_lib.py", line 37, in __init__
    model_fn, self.model_package = self.get_keras_apps_model(args[MODEL_NAME])
  File "/data1/work/Ming/MCT/model_optimization/tutorials/quick_start/keras_fw/keras_applications/model_lib.py", line 66, in get_keras_apps_model
    raise Exception(f'Unknown Keras Applications model class {model_name}')
Exception: Unknown Keras Applications model class resnet50.ResNet50
```

### Code to reproduce the issue

```shell
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    float_acc, quant_acc, quant_info, dataset_info = quantization_flow(config)
  File "main.py", line 94, in quantization_flow
    ml = model_lib.ModelLib(config)
  File "/data1/work/Ming/MCT/model_optimization/tutorials/quick_start/keras_fw/keras_applications/model_lib.py", line 37, in __init__
    model_fn, self.model_package = self.get_keras_apps_model(args[MODEL_NAME])
  File "/data1/work/Ming/MCT/model_optimization/tutorials/quick_start/keras_fw/keras_applications/model_lib.py", line 66, in get_keras_apps_model
    raise Exception(f'Unknown Keras Applications model class {model_name}')
Exception: Unknown Keras Applications model class resnet50.ResNet50
```

**Comment by Idan-BenAmi** [comment]
Hi @Ming-Ivy ,
Thank you for your feedback.
The correct command line for "keras_applications" should be without the prefix "resnet50" in the model name:
python main.py --model_name ResNet50 --model_library keras_applications [...]
We noticed that our documentation is misleading and we will fix it as soon as possible.
Thanks
Idan

**Comment by Ming-Ivy** [comment]
> Hi @Ming-Ivy , Thank you for your feedback. The correct command line for "keras_applications" should be without the prefix "resnet50" in the model name: python main.py --model_name ResNet50 --model_library keras_applications [...] We noticed that our documentation is misleading and we will fix it as soon as possible. Thanks Idan

Thank you for your answer Idan, 
I just tried the comment: python main.py --model_name ResNet50 --model_library keras_applications [...]
And it comes out:
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    float_acc, quant_acc, quant_info, dataset_info = quantization_flow(config)
  File "main.py", line 96, in quantization_flow
    ml = model_lib.ModelLib(config)
  File "/data1/work/Ming/MCT/MCT_MoblieNetv2-SSDlite/model_optimization/tutorials/quick_start/keras_fw/keras_applications/model_lib.py", line 40, in __init__
    self.model = model_fn()
TypeError: 'tuple' object is not callable

The error line code in /keras_applications/model_lib is:        
       model_fn, self.model_package = self.get_keras_apps_model(args[MODEL_NAME])
        self.model = model_fn()

would you please help with that problem? Appreciate for that

**Comment by Idan-BenAmi** [comment]
Hi again,
Can you specify the "keras" version you are using?
Thanks
Idan

**Comment by Ming-Ivy** [comment]
Hi Idan,

keras version is 2.13.1, thank you for your help.

Ming

**Comment by Idan-BenAmi** [comment]
Hi @Ming-Ivy ,
Sadly I wasn't able to reproduce the error you encountered using "keras==2.13.1"

I suggest the following:
We have this tutorial which demonstrates how to quantize a "mobilenet_v2" model - https://github.com/sony/model_optimization/blob/main/tutorials/notebooks/pytorch/example_quick_start_torchvision.ipynb
Will you be able to use it in "google colab" (you have a link in the tutorial), and edit the following for your ResNet50:
1. After the 2nd code section, add a new section with the following code, which applies MCT==1.11 and keras==2.13.1: 
```
!pip install tensorflow==2.13.1
!cd ./local_mct/ && git rebase --onto bca5634 && cd - 
!pip list | grep keras
```
 2. Replace the python command in the 5th code section with the following: 
` !python ./local_mct/tutorials/quick_start/main.py --model_name ResNet50 --model_library keras_applications --validation_dataset_folder ./imagenet/val --representative_dataset_folder ./imagenet/val`

Let me know if it works for you.
Idan
