### ISSUE TITLE
The size of the quantized model

### ISSUE THREAD

**Issue by Ming-Ivy** [sony/model_optimization#960]
### Issue Type

Performance

### Source

source

### MCT Version

1.10.0

### Describe the issue

```shell
I would like to know the output of mct. I have tried different model and found that the size of quantized model .onnx/.tflite is nearly the same as original model, but in your main.py code, the output Size is 1/4 of original model. it seems only caculate weights memory in QuantInfo.user_info.final_kpi.weights_memory . I just wondering when I use Resnet18, Model size is 44.59mb, quantized model size is 44.57mb, why the size does not decrease to 1/4 but only a little?
```

### Code to reproduce the issue

```shell
This is the code to caculate the size.

def model_size_in_mb(model):
    param_size = 0
    if hasattr(model, 'parameters'):  # PyTorch model
        for param in model.parameters():
            param_size += param.numel() * param.element_size()
    elif hasattr(model, 'trainable_variables'):  # TensorFlow/Keras model
        for var in model.trainable_variables:
            param_size += tf.size(var).numpy() * var.dtype.size
    return param_size / (1024 ** 2)
```

**Comment by ofirgo** [comment]
Hello @Ming-Ivy ,

Thank you for your question.

The observed lack of reduction in model size upon quantization is due to the fact that the exported model from MCT undergoes a process known as fake quantization. In this process, the weights are maintained in floating-point format, but each channel represents values that have been quantized to 8 bits, allowing for a maximum of 256 different values.

The total memory reported in the QuantInfo.user_info.final_kpi objects takes into account this quantization. It aggregates the parameters of each channel as if they were represented in 8 bits, resulting in a final size that is 1/4 of the total size (representing an 8-bit instead of 32-bit float representation).

This explains why, despite the quantization, the exported model size remains largely unchanged.

**Comment by Ming-Ivy** [comment]
> Hello @Ming-Ivy ,
> 
> Thank you for your question.
> 
> The observed lack of reduction in model size upon quantization is due to the fact that the exported model from MCT undergoes a process known as fake quantization. In this process, the weights are maintained in floating-point format, but each channel represents values that have been quantized to 8 bits, allowing for a maximum of 256 different values.
> 
> The total memory reported in the QuantInfo.user_info.final_kpi objects takes into account this quantization. It aggregates the parameters of each channel as if they were represented in 8 bits, resulting in a final size that is 1/4 of the total size (representing an 8-bit instead of 32-bit float representation).
> 
> This explains why, despite the quantization, the exported model size remains largely unchanged.

Hi， thank you for your answer.  
In that way, in main.py, the size shown in res['Size[MB]'] = round(quant_info.user_info.final_kpi.weights_memory / 1e6, 2) is the real size after quantization? or only the size of weights_memory? bias or activation change will not affect the size output in main.py?

**Comment by ofirgo** [comment]
> > Hello @Ming-Ivy ,
> > Thank you for your question.
> > The observed lack of reduction in model size upon quantization is due to the fact that the exported model from MCT undergoes a process known as fake quantization. In this process, the weights are maintained in floating-point format, but each channel represents values that have been quantized to 8 bits, allowing for a maximum of 256 different values.
> > The total memory reported in the QuantInfo.user_info.final_kpi objects takes into account this quantization. It aggregates the parameters of each channel as if they were represented in 8 bits, resulting in a final size that is 1/4 of the total size (representing an 8-bit instead of 32-bit float representation).
> > This explains why, despite the quantization, the exported model size remains largely unchanged.
> 
> Hi， thank you for your answer. In that way, in main.py, the size shown in res['Size[MB]'] = round(quant_info.user_info.final_kpi.weights_memory / 1e6, 2) is the real size after quantization? or only the size of weights_memory? bias or activation change will not affect the size output in main.py? In that case, how can I aquire the real size of int8 ?

Yes, the reported `weights_memory` size in the `user_info` results pertains to the sum of all quantized kernels of linear operations in the model. It's important to note that the size of biases is not included in this computation.

Additionally, within the same object, you can find the final activation memory size (`quant_info.user_info.final_kpi.activation_memory`). It's worth mentioning that the activation memory size is dependent on the inference execution process and scheduling. As a result, we adopt a simplified approach and consider the maximal activation tensor as the activation memory of the model.

Moreover, MCT offers the capability to export models to INT8 in tflite format. Such a model will have the actual size of an INT8 quantized model.

To export a model to INT8, you can follow this tutorial: [INT8 tflite export](https://colab.research.google.com/github/sony/model_optimization/blob/main/tutorials/notebooks/keras/export/example_keras_export.ipynb#scrollTo=-L1aRxFGGFeF).

Let me know if you have any other questions.

**Comment by Ming-Ivy** [comment]
> > > Hello @Ming-Ivy ,
> > > Thank you for your question.
> > > The observed lack of reduction in model size upon quantization is due to the fact that the exported model from MCT undergoes a process known as fake quantization. In this process, the weights are maintained in floating-point format, but each channel represents values that have been quantized to 8 bits, allowing for a maximum of 256 different values.
> > > The total memory reported in the QuantInfo.user_info.final_kpi objects takes into account this quantization. It aggregates the parameters of each channel as if they were represented in 8 bits, resulting in a final size that is 1/4 of the total size (representing an 8-bit instead of 32-bit float representation).
> > > This explains why, despite the quantization, the exported model size remains largely unchanged.
> > 
> > 
> > Hi， thank you for your answer. In that way, in main.py, the size shown in res['Size[MB]'] = round(quant_info.user_info.final_kpi.weights_memory / 1e6, 2) is the real size after quantization? or only the size of weights_memory? bias or activation change will not affect the size output in main.py? In that case, how can I aquire the real size of int8 ?
> 
> Yes, the reported `weights_memory` size in the `user_info` results pertains to the sum of all quantized kernels of linear operations in the model. It's important to note that the size of biases is not included in this computation.
> 
> Additionally, within the same object, you can find the final activation memory size (`quant_info.user_info.final_kpi.activation_memory`). It's worth mentioning that the activation memory size is dependent on the inference execution process and scheduling. As a result, we adopt a simplified approach and consider the maximal activation tensor as the activation memory of the model.
> 
> Moreover, MCT offers the capability to export models to INT8 in tflite format. Such a model will have the actual size of an INT8 quantized model.
> 
> To export a model to INT8, you can follow this tutorial: [INT8 tflite export](https://colab.research.google.com/github/sony/model_optimization/blob/main/tutorials/notebooks/keras/export/example_keras_export.ipynb#scrollTo=-L1aRxFGGFeF).
> 
> Let me know if you have any other questions.

Thank you so much for your help!!
