### ISSUE TITLE
Include nightly build version information in `__version__`

### ISSUE THREAD

**Issue by jgerityneurala** [sony/model_optimization#998]
### Issue Type

Feature Request

### Source

pip (mct-nightly)

### MCT Version

1.9.0.20230830.post74713

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.8.10

### Describe the issue

We have written some code that depends on the Keras quantization facade, which [recently had some API change from `_experimental` to official](https://github.com/sony/model_optimization/commit/a609a8b2b9ace70d2f54c6510ea18f8704c5a1c3#diff-9f3901db7ebd8d98d5d35c4459b326de17b43e2343e0456eaf5492406480294aR88). However, there is no corresponding mechanism to tell _at runtime_ what MCT version we have that can be used to distinguish between these two names. What we currently do is pin a particular version of the `mct-nightly` and walk it forward gradually, and we expect another lurch forward soon that will probably run into this naming change.

Our workaround is to collapse the two names onto a common internal name, trying `_experimental` first and falling back on official if that fails.

It is possible to use `importlib.metadata.version("mct-nightly")` to test the version of the nightly we have, but it would be even more convenient if `model_compression_toolkit.__version__` were populated with more a granular version in nightly builds, which would allow us to write the same version-introspection code regardless of whether we're using `mct-nightly` or the official releases of `model_compression_toolkit`.

### Expected behaviour

Ideally `model_compression_toolkit.__version__` and the output of `pip show mct-nightly | grep Version` would agree:

```
$ pip show mct-nightly | grep Version
Version: 1.11.0.20240305.post352
...
$ # I would prefer 1.11.0.20240305.post352 here instead
$ python -c "import model_compression_toolkit as mct; print(mct.__version__)"
1.11.0
```

### Code to reproduce the issue

```shell
import model_compression_toolkit as mct

# fails on mct-nightly>=1.11.0.20240306.post426
quantize_func = mct.ptq.keras_post_training_quantization_experimental
```

**Comment by reuvenperetz** [comment]
Hi @jgerityneurala,
Thanks for your contribution!
